

export const carBrands =
[ 'Acura',
  'Alfa Romeo',
  'AM General',
  'Aston Martin',
  'Audi',
  'Bentley',
  'BMW',
  'Bugatti',
  'Buick',
  'Byton',
  'Cadillac',
  'Chevrolet',
  'Chrysler',
  'Daewoo',
  'Dodge',
  'Eagle',
  'Ferrari',
  'Fiat',
  'Fisker',
  'Ford',
  'Genesis',
  'GEO',
  'GMC',
  'Honda',
  'Hummer',
  'Hyundai',
  'Infiniti',
  'Isuzu',
  'Jaguar',
  'Jeep',
  'Kia',
  'Lamborghini',
  'Land Rover',
  'Lexus',
  'Lincoln',
  'Lotus',
  'Lucid',
  'Maserati',
  'Maybach',
  'Mazda',
  'Mclaren',
  'Mercedes Benz',
  'Mercury',
  'Mini',
  'Mitsubishi',
  'Nissan',
  'Oldsmobile',
  'Panoz',
  'Plymouth',
  'Polestar',
  'Pontiac',
  'Porsche',
  'Ram',
  'Rivian',
  'Rolls Royce',
  'Saab',
  'Saturn',
  'Scion',
  'Smart',
  'Spyker',
  'Subaru',
  'Suzuki',
  'Tesla',
  'Toyota',
  'Volkswagen',
  'Volvo' ]

export const carYears = [1990, 1991, 1992, 1993, 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022,2023]


export const carsAllYear = 
[ 'acura',
  'alfa-romeo',
  'am-general',
  'aston-martin',
  'audi',
  'bentley',
  'bmw',
  'bugatti',
  'buick',
  'byton',
  'cadillac',
  'chevrolet',
  'chrysler',
  'daewoo',
  'dodge',
  'eagle',
  'ferrari',
  'fiat',
  'fisker',
  'ford',
  'genesis',
  'geo',
  'gmc',
  'honda',
  'hummer',
  'hyundai',
  'infiniti',
  'isuzu',
  'jaguar',
  'jeep',
  'kia',
  'lamborghini',
  'land-rover',
  'lexus',
  'lincoln',
  'lotus',
  'lucid',
  'maserati',
  'maybach',
  'mazda',
  'mclaren',
  'mercedes-benz',
  'mercury',
  'mini',
  'mitsubishi',
  'nissan',
  'oldsmobile',
  'panoz',
  'plymouth',
  'polestar',
  'pontiac',
  'porsche',
  'ram',
  'rivian',
  'rolls-royce',
  'saab',
  'saturn',
  'scion',
  'smart',
  'spyker',
  'subaru',
  'suzuki',
  'tesla',
  'toyota',
  'volkswagen',
  'volvo' ]

export const carTypes = ["Sedan", "Coupe", "SUV", "Minivan", "Wagon", "Sport", "Station Wagon", "Hatchback", "Convertible", "Pickup Truck"]