
export const carTempData = [
        {
            "name": "2020 Ford Shelby GT500",
            "engine": "5.2L Supercharged V8",
            "hoursepower": 760,
            "price": "70,300",
            "videoId": "QHLojVxs-M0",
            "logoUrl": "Ford_Logo.png",
            "youtube": {"snippet":{
                "title": "Here's Why I Want A 2020 Shelby GT500!"
            }},
            "creator": "EddieX",
            "fans": '30k',
            "profile_pic": "https://yt3.ggpht.com/a/AATXAJzxcCWM9He6uumiLOa71zR_7mR3feUT_MG2IfBY=s176-c-k-c0xffffffff-no-rj-mo",
        },
        {
            "name": "2014 Mercedes-Benz SLS AMG",
            "engine": "6.2 L V8",
            "hoursepower": 622,
            "price": "386,588",
            "videoId": "ifi5cGgJa7s",
            "logoUrl": "MercedesBenz_Logo.png",
            "youtube": {"snippet":{
                "title": "The Best Mercedes AMG Ever! | SLS Black Series Review",
            }},
            "creator": "EddieX",
            "fans": '30k',
            "profile_pic": "https://yt3.ggpht.com/a/AATXAJzxcCWM9He6uumiLOa71zR_7mR3feUT_MG2IfBY=s176-c-k-c0xffffffff-no-rj-mo",
        },
        
    ]

export const carBrands =[
    "Acura",
    "Alfa Romeo",
    "Aston Martin",
    "Audi",
    "Bentley",
    "BMW",
    "Bugatti",
    "Buick",
    "Cadillac",
    "Chevrolet",
    "Chrysler",
    "Dodge",
    "Ferrari",
    "Fiat",
    "Ford",
    "GMC",
    "Genesis",
    "Honda",
    "Hyundai",
    "Infiniti",
    "Jaguar",
    "Jeep",
    "Kia",
    "Lamborghini", 
    "Land Rover",
    "Lexus",
    "Lincoln",
    "Lotus",
    "Mclaren",
    "Maserati",
    "Mazda",
    "Mercedes-Benz",
    "Mercury",
    "Mini",
    "Mitsubishi",
    // "Nikola",
    "Nissan",
    "Polestar",
    "Pontiac",
    "Porsche",
    "Ram",
    "Rivian",
    "Rolls-Royce",
    "Saab",
    "Saturn",
    "Scion",
    "Smart",
    "Subaru",
    "Suzuki",
    "Tesla",
    "Toyota",
    "Volkswagen",
    "Volvo"
]

export const carYears = [1990, 1991, 1992, 1993, 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022,2023]


export const carsAllYear = [ 'acura',
  'alfa-romeo',
  'am-general',
  'aston-martin',
  'audi',
  'bentley',
  'bmw',
  'bugatti',
  'byton',
  'cadillac',
  'chevrolet',
  'chrysler',
  'daewoo',
  'dodge',
  'eagle',
  'ferrari',
  'fisker',
  'ford',
  'geo',
  'genesis',
  'gmc',
  'honda',
  'hummer',
  'hyundai',
  'infiniti',
  'isuzu',
  'jaguar',
  'jeep',
  'kia',
  'lamborghini',
  'land-rover',
  'lexus',
  'lucid',
  'maserati',
  'maybach',
  'mazda',
  'mclaren',
  'mercedes-benz',
  'mercury',
  'mini',
  'mitsubishi',
  'nissan',
  'oldsmobile',
  'panoz',
  'plymouth',
  'polestar',
  'pontiac',
  'porsche',
  'ram',
  'rivian',
  'rolls-royce',
  'saab',
  'saturn',
  'scion',
  'smart',
  'spyker',
  'suzuki',
  'tesla',
  'toyota',
  'volkswagen',
  'volvo' ]

export const carTypes = ["Sedan", "Coupe", "SUV", "Minivan", "Wagon", "Sport", "Station Wagon", "Hatchback", "Convertible", "Pickup Truck"]